services:
  api:
    build: .
    container_name: detect-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - CONNECTION_STRING=${CONNECTION_STRING}
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
volumes:
  mongo_data: