version: "3.9"

services:
  api:
    build: .
    container_name: detect-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CONNECTION_STRING=mongodb://mongo:27017/cloak
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: